ipset=/1018213540.rsc.cdn77.org/pbr-intrus
ipset=/alfabank.ru/pbr-intrus
ipset=/avito.ru/pbr-intrus
ipset=/avtodor-tr.ru/pbr-intrus
ipset=/b2c-ticket-sentry.onelya.ru/pbr-intrus
ipset=/bitrix.info/pbr-intrus
ipset=/bkvet.ru/pbr-intrus
ipset=/cdn1.ozonusercontent.com/pbr-intrus
ipset=/cdn.ngenix.net/pbr-intrus
ipset=/cms1.dzvr.ru/pbr-intrus
ipset=/consultant.ru/pbr-intrus
ipset=/dns-shop.ru/pbr-intrus
ipset=/dzvr.ru/pbr-intrus
ipset=/emex.ru/pbr-intrus
ipset=/fairplay-proxy.ott.yandex.ru/pbr-intrus
ipset=/gorzdrav.spb.ru/pbr-intrus
ipset=/gosuslugi.ru/pbr-intrus
ipset=/gov.ru/pbr-intrus
ipset=/graphql.kinopoisk.ru/pbr-intrus
ipset=/gu-st.ru/pbr-intrus
ipset=/iptv.rt.ru/pbr-intrus
ipset=/lemanapro.ru/pbr-intrus
ipset=/leroymerlin.ru/pbr-intrus
ipset=/magnit.ru/pbr-intrus
ipset=/mobileapp.russianpost.ru/pbr-intrus
ipset=/mosenergosbyt.ru/pbr-intrus
ipset=/mosreg.ru/pbr-intrus
ipset=/mos.ru/pbr-intrus
ipset=/nalog.ru/pbr-intrus
ipset=/ozon.ru/pbr-intrus
ipset=/pesc.ru/pbr-intrus
ipset=/pochta.ru/pbr-intrus
ipset=/reso.ru/pbr-intrus
ipset=/rosreestr.gov.ru/pbr-intrus
ipset=/rtbcdn.ru/pbr-intrus
ipset=/rutubelist.ru/pbr-intrus
ipset=/rutube.ru/pbr-intrus
ipset=/rzd-bonus.ru/pbr-intrus
ipset=/rzd.ru/pbr-intrus
ipset=/spb.ru/pbr-intrus
ipset=/sys.refocus.ru/pbr-intrus
ipset=/vshark.ttk.ru/pbr-intrus
ipset=/widevine-proxy.ott.yandex.ru/pbr-intrus
ipset=/xn--90aijkdmaud0d.xn--p1ai/pbr-intrus
